from linkedlist import LinkedList

l1 = LinkedList()
l1.add(1)
l1.add(3)
l1.add(5)
l1.add(3)
l1.add(1)
print("Test si la liste chaînée simple [1,3,5,3,1] est palindromique.")
l1.traverse_list()
print("Is palindrome?", l1.is_palindrome())
print()

l2 = LinkedList()
l2.add(1)
l2.add(3)
l2.add(5)
l2.add(5)
l2.add(3)
l2.add(1)
print("Test si la liste chaînée simple [1,3,5,5,3,1] est palindromique.")
l2.traverse_list()
print("Is palindrome?", l2.is_palindrome())
print()

l3 = LinkedList()
l3.add(1)
l3.add(3)
l3.add(5)
l3.add(5)
l3.add(3)
l3.add(0)
print("Test si la liste chaînée simple [1,3,5,5,3,0] est palindromique.")
l3.traverse_list()
print("Is palindrome?", l3.is_palindrome())
print()
